web_app:
    host: localhost
    port: 8888

pagination:
    max_movies_per_search: 10

mongo_connection:
    user: uber
    password: NWE0MDgyOThlY2UyNDY4ZjgyZjZlZjky
    host: 192.168.1.107
    port: 27017
    name: uber
